### ISSUE TITLE
Search-01 Search Function will include all restaurants in the results when search input is a space + a period (" .")

### ISSUE THREAD

**Issue by LouisD69** [jasonevangelista/stsweng-zarap#38] opened 2021-01-15 11:35 UTC
|  
-- | --
ID | Search-01
Title | [Search] Search Function will return all restaurants in the results when search input is a space + a period (" .")
Reporter | Team Rocket (Dela Cruz)
Date | Jan 15, 2021
Environment | Windows 10 - Microsoft Edge
Priority level | Low

**Steps to Reproduce:**
1. Using the homepage search bar, type " ."
2. Hit enter / Click the search button

**Expected Result:**
The search result should be empty because there is no such restaurant with the name or similar to " ."

**Actual Result:**
All restaurants are included in the results

**Screenshots:** 
![image](https://user-images.githubusercontent.com/61369999/104721072-4aea0c80-5768-11eb-82a0-1544b9a6f87a.png)
![image](https://user-images.githubusercontent.com/61369999/104721132-5f2e0980-5768-11eb-8e69-81766522786f.png)

.

**Comment by carlosshi1** [comment] 2021-01-15 14:55
Space input matches the regex of all search results with spaces in it (starbucks does not appear), period (.) and symbol related bugs will be fixed in #39

**Comment by carlosshi1** [comment] 2021-01-15 14:57
In addition, inputting "star." will output Starbucks as intended

**Closed as completed** 2021-01-31 05:40 UTC
Labels: invalid
